services:
  - type: web
    name: xunshanapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_production.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /

databases:
  - name: xunshanapp-db
    databaseName: xunshanapp
    user: xunshanapp
    plan: free 